[SETTINGS]
$search_resources	resources_only
$resources_output	.\res
$nls_internal_time	UTC

[RESOURCES]
.\res
usys:uidf.uar

[FILES]
usys:*.xml		usysuniface:.\misc\*.xml

*.css			.\css\*.css
*.dtd			.\dtd\*.dtd
*.exp			.\exp\*.exp
*.c			.\hdr\*.c
*.h			.\hdr\*.h
*.htm			.\htm\*.htm
*.html			.\htm\*.html
*.gif			.\img\*.gif
*.jpg			.\img\*.jpg
*.png			.\img\*.png
*.js			.\js\*.js
*.log			.\log\*.log
*.*lst			.\lst\*.*lst
*.sql			.\sql\*.sql
*.xml			.\xml\*.xml

#file .\adm\dbms.asn
