[DRIVER_SETTINGS]
SLE		U1.0
USYS$SLE_PARAMS	create db = on, identifiers = quoted

[PATHS]
; Path to the SQLite database for the Uniface Repository:
$DBMS		SLE:.\dbs\uniface_repo.db
; Path to the SQLite database for application data:
$DBMS_DEF	SLE:.\dbs\uniface_data.db

$SYS		$DBMS
$UUU		$DBMS
$IDF		$DBMS
$DEF		$DBMS_DEF

$SLE		$DEF
